/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerCreateAttributeOptionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerCreateAttributeOptionsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerCreateAttributeOptionsResponse
        //private EntitymanagerCreateAttributeOptionsResponse instance;

        public EntitymanagerCreateAttributeOptionsResponseTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerCreateAttributeOptionsResponse
            //instance = new EntitymanagerCreateAttributeOptionsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerCreateAttributeOptionsResponse
        /// </summary>
        [Fact]
        public void EntitymanagerCreateAttributeOptionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerCreateAttributeOptionsResponse
            //Assert.IsType<EntitymanagerCreateAttributeOptionsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
