/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerAttributeWriteError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerAttributeWriteErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerAttributeWriteError
        //private EntitymanagerAttributeWriteError instance;

        public EntitymanagerAttributeWriteErrorTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerAttributeWriteError
            //instance = new EntitymanagerAttributeWriteError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerAttributeWriteError
        /// </summary>
        [Fact]
        public void EntitymanagerAttributeWriteErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerAttributeWriteError
            //Assert.IsType<EntitymanagerAttributeWriteError>(instance);
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

        /// <summary>
        /// Test the property 'AttributeCode'
        /// </summary>
        [Fact]
        public void AttributeCodeTest()
        {
            // TODO unit test for the property 'AttributeCode'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
