/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerCreateEntityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerCreateEntityResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerCreateEntityResponse
        //private EntitymanagerCreateEntityResponse instance;

        public EntitymanagerCreateEntityResponseTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerCreateEntityResponse
            //instance = new EntitymanagerCreateEntityResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerCreateEntityResponse
        /// </summary>
        [Fact]
        public void EntitymanagerCreateEntityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerCreateEntityResponse
            //Assert.IsType<EntitymanagerCreateEntityResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AttributeWriteErrors'
        /// </summary>
        [Fact]
        public void AttributeWriteErrorsTest()
        {
            // TODO unit test for the property 'AttributeWriteErrors'
        }

        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Fact]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }
    }
}
