/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerUpdateAttributeRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerUpdateAttributeRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerUpdateAttributeRequestPayload
        //private EntitymanagerUpdateAttributeRequestPayload instance;

        public EntitymanagerUpdateAttributeRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerUpdateAttributeRequestPayload
            //instance = new EntitymanagerUpdateAttributeRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerUpdateAttributeRequestPayload
        /// </summary>
        [Fact]
        public void EntitymanagerUpdateAttributeRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerUpdateAttributeRequestPayload
            //Assert.IsType<EntitymanagerUpdateAttributeRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'VarDefault'
        /// </summary>
        [Fact]
        public void VarDefaultTest()
        {
            // TODO unit test for the property 'VarDefault'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'GroupCode'
        /// </summary>
        [Fact]
        public void GroupCodeTest()
        {
            // TODO unit test for the property 'GroupCode'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'RenderAs'
        /// </summary>
        [Fact]
        public void RenderAsTest()
        {
            // TODO unit test for the property 'RenderAs'
        }
    }
}
