/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerRenderAs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerRenderAsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerRenderAs
        //private EntitymanagerRenderAs instance;

        public EntitymanagerRenderAsTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerRenderAs
            //instance = new EntitymanagerRenderAs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerRenderAs
        /// </summary>
        [Fact]
        public void EntitymanagerRenderAsInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerRenderAs
            //Assert.IsType<EntitymanagerRenderAs>(instance);
        }
    }
}
