/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerEntityIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerEntityIdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerEntityIdentifier
        //private EntitymanagerEntityIdentifier instance;

        public EntitymanagerEntityIdentifierTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerEntityIdentifier
            //instance = new EntitymanagerEntityIdentifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerEntityIdentifier
        /// </summary>
        [Fact]
        public void EntitymanagerEntityIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerEntityIdentifier
            //Assert.IsType<EntitymanagerEntityIdentifier>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
