/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerOptionsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerOptionsListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerOptionsList
        //private EntitymanagerOptionsList instance;

        public EntitymanagerOptionsListTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerOptionsList
            //instance = new EntitymanagerOptionsList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerOptionsList
        /// </summary>
        [Fact]
        public void EntitymanagerOptionsListInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerOptionsList
            //Assert.IsType<EntitymanagerOptionsList>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
