/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerBulkCreateAttributeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerBulkCreateAttributeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerBulkCreateAttributeResponse
        //private EntitymanagerBulkCreateAttributeResponse instance;

        public EntitymanagerBulkCreateAttributeResponseTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerBulkCreateAttributeResponse
            //instance = new EntitymanagerBulkCreateAttributeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerBulkCreateAttributeResponse
        /// </summary>
        [Fact]
        public void EntitymanagerBulkCreateAttributeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerBulkCreateAttributeResponse
            //Assert.IsType<EntitymanagerBulkCreateAttributeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
    }
}
