/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerListEntitiesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerListEntitiesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerListEntitiesRequest
        //private EntitymanagerListEntitiesRequest instance;

        public EntitymanagerListEntitiesRequestTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerListEntitiesRequest
            //instance = new EntitymanagerListEntitiesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerListEntitiesRequest
        /// </summary>
        [Fact]
        public void EntitymanagerListEntitiesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerListEntitiesRequest
            //Assert.IsType<EntitymanagerListEntitiesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
    }
}
