/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerAttribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerAttributeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerAttribute
        //private EntitymanagerAttribute instance;

        public EntitymanagerAttributeTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerAttribute
            //instance = new EntitymanagerAttribute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerAttribute
        /// </summary>
        [Fact]
        public void EntitymanagerAttributeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerAttribute
            //Assert.IsType<EntitymanagerAttribute>(instance);
        }

        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Fact]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'OptionList'
        /// </summary>
        [Fact]
        public void OptionListTest()
        {
            // TODO unit test for the property 'OptionList'
        }

        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Fact]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }

        /// <summary>
        /// Test the property 'VarDefault'
        /// </summary>
        [Fact]
        public void VarDefaultTest()
        {
            // TODO unit test for the property 'VarDefault'
        }

        /// <summary>
        /// Test the property 'IsRequired'
        /// </summary>
        [Fact]
        public void IsRequiredTest()
        {
            // TODO unit test for the property 'IsRequired'
        }

        /// <summary>
        /// Test the property 'IsSystem'
        /// </summary>
        [Fact]
        public void IsSystemTest()
        {
            // TODO unit test for the property 'IsSystem'
        }

        /// <summary>
        /// Test the property 'IsRepeated'
        /// </summary>
        [Fact]
        public void IsRepeatedTest()
        {
            // TODO unit test for the property 'IsRepeated'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'GroupCode'
        /// </summary>
        [Fact]
        public void GroupCodeTest()
        {
            // TODO unit test for the property 'GroupCode'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'RenderAs'
        /// </summary>
        [Fact]
        public void RenderAsTest()
        {
            // TODO unit test for the property 'RenderAs'
        }
    }
}
