/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerGetAttributeOptionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerGetAttributeOptionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerGetAttributeOptionResponse
        //private EntitymanagerGetAttributeOptionResponse instance;

        public EntitymanagerGetAttributeOptionResponseTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerGetAttributeOptionResponse
            //instance = new EntitymanagerGetAttributeOptionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerGetAttributeOptionResponse
        /// </summary>
        [Fact]
        public void EntitymanagerGetAttributeOptionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerGetAttributeOptionResponse
            //Assert.IsType<EntitymanagerGetAttributeOptionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Option'
        /// </summary>
        [Fact]
        public void OptionTest()
        {
            // TODO unit test for the property 'Option'
        }
    }
}
