/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerEntityRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerEntityRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerEntityRequest
        //private EntitymanagerEntityRequest instance;

        public EntitymanagerEntityRequestTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerEntityRequest
            //instance = new EntitymanagerEntityRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerEntityRequest
        /// </summary>
        [Fact]
        public void EntitymanagerEntityRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerEntityRequest
            //Assert.IsType<EntitymanagerEntityRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'EntityData'
        /// </summary>
        [Fact]
        public void EntityDataTest()
        {
            // TODO unit test for the property 'EntityData'
        }

        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Fact]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }
    }
}
