/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerUpdateOptionsListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerUpdateOptionsListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerUpdateOptionsListResponse
        //private EntitymanagerUpdateOptionsListResponse instance;

        public EntitymanagerUpdateOptionsListResponseTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerUpdateOptionsListResponse
            //instance = new EntitymanagerUpdateOptionsListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerUpdateOptionsListResponse
        /// </summary>
        [Fact]
        public void EntitymanagerUpdateOptionsListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerUpdateOptionsListResponse
            //Assert.IsType<EntitymanagerUpdateOptionsListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'OptionList'
        /// </summary>
        [Fact]
        public void OptionListTest()
        {
            // TODO unit test for the property 'OptionList'
        }
    }
}
