/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerAttributeOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerAttributeOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerAttributeOption
        //private EntitymanagerAttributeOption instance;

        public EntitymanagerAttributeOptionTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerAttributeOption
            //instance = new EntitymanagerAttributeOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerAttributeOption
        /// </summary>
        [Fact]
        public void EntitymanagerAttributeOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerAttributeOption
            //Assert.IsType<EntitymanagerAttributeOption>(instance);
        }

        /// <summary>
        /// Test the property 'Option'
        /// </summary>
        [Fact]
        public void OptionTest()
        {
            // TODO unit test for the property 'Option'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Swatches'
        /// </summary>
        [Fact]
        public void SwatchesTest()
        {
            // TODO unit test for the property 'Swatches'
        }
    }
}
