/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerListEntitiesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerListEntitiesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerListEntitiesResponse
        //private EntitymanagerListEntitiesResponse instance;

        public EntitymanagerListEntitiesResponseTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerListEntitiesResponse
            //instance = new EntitymanagerListEntitiesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerListEntitiesResponse
        /// </summary>
        [Fact]
        public void EntitymanagerListEntitiesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerListEntitiesResponse
            //Assert.IsType<EntitymanagerListEntitiesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Entities'
        /// </summary>
        [Fact]
        public void EntitiesTest()
        {
            // TODO unit test for the property 'Entities'
        }

        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
    }
}
