/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerUpdateAttributeGroupRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerUpdateAttributeGroupRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerUpdateAttributeGroupRequestPayload
        //private EntitymanagerUpdateAttributeGroupRequestPayload instance;

        public EntitymanagerUpdateAttributeGroupRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerUpdateAttributeGroupRequestPayload
            //instance = new EntitymanagerUpdateAttributeGroupRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerUpdateAttributeGroupRequestPayload
        /// </summary>
        [Fact]
        public void EntitymanagerUpdateAttributeGroupRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerUpdateAttributeGroupRequestPayload
            //Assert.IsType<EntitymanagerUpdateAttributeGroupRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'Visibility'
        /// </summary>
        [Fact]
        public void VisibilityTest()
        {
            // TODO unit test for the property 'Visibility'
        }
    }
}
