/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerTypesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerTypes
        //private EntitymanagerTypes instance;

        public EntitymanagerTypesTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerTypes
            //instance = new EntitymanagerTypes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerTypes
        /// </summary>
        [Fact]
        public void EntitymanagerTypesInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerTypes
            //Assert.IsType<EntitymanagerTypes>(instance);
        }
    }
}
