/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing EntitymanagerGetAttributeOptionsResponseOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntitymanagerGetAttributeOptionsResponseOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EntitymanagerGetAttributeOptionsResponseOption
        //private EntitymanagerGetAttributeOptionsResponseOption instance;

        public EntitymanagerGetAttributeOptionsResponseOptionTests()
        {
            // TODO uncomment below to create an instance of EntitymanagerGetAttributeOptionsResponseOption
            //instance = new EntitymanagerGetAttributeOptionsResponseOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EntitymanagerGetAttributeOptionsResponseOption
        /// </summary>
        [Fact]
        public void EntitymanagerGetAttributeOptionsResponseOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EntitymanagerGetAttributeOptionsResponseOption
            //Assert.IsType<EntitymanagerGetAttributeOptionsResponseOption>(instance);
        }

        /// <summary>
        /// Test the property 'ListCode'
        /// </summary>
        [Fact]
        public void ListCodeTest()
        {
            // TODO unit test for the property 'ListCode'
        }

        /// <summary>
        /// Test the property 'Option'
        /// </summary>
        [Fact]
        public void OptionTest()
        {
            // TODO unit test for the property 'Option'
        }
    }
}
