/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkRemoveAssetsEntriesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkRemoveAssetsEntriesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkRemoveAssetsEntriesRequest
        //private ProductBulkRemoveAssetsEntriesRequest instance;

        public ProductBulkRemoveAssetsEntriesRequestTests()
        {
            // TODO uncomment below to create an instance of ProductBulkRemoveAssetsEntriesRequest
            //instance = new ProductBulkRemoveAssetsEntriesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkRemoveAssetsEntriesRequest
        /// </summary>
        [Fact]
        public void ProductBulkRemoveAssetsEntriesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkRemoveAssetsEntriesRequest
            //Assert.IsType<ProductBulkRemoveAssetsEntriesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
    }
}
