/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkUpdateResponseResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkUpdateResponseResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkUpdateResponseResponse
        //private ProductBulkUpdateResponseResponse instance;

        public ProductBulkUpdateResponseResponseTests()
        {
            // TODO uncomment below to create an instance of ProductBulkUpdateResponseResponse
            //instance = new ProductBulkUpdateResponseResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkUpdateResponseResponse
        /// </summary>
        [Fact]
        public void ProductBulkUpdateResponseResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkUpdateResponseResponse
            //Assert.IsType<ProductBulkUpdateResponseResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
    }
}
