/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductUpdateProductRequestV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductUpdateProductRequestV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductUpdateProductRequestV2
        //private ProductUpdateProductRequestV2 instance;

        public ProductUpdateProductRequestV2Tests()
        {
            // TODO uncomment below to create an instance of ProductUpdateProductRequestV2
            //instance = new ProductUpdateProductRequestV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductUpdateProductRequestV2
        /// </summary>
        [Fact]
        public void ProductUpdateProductRequestV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductUpdateProductRequestV2
            //Assert.IsType<ProductUpdateProductRequestV2>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'AttributesMask'
        /// </summary>
        [Fact]
        public void AttributesMaskTest()
        {
            // TODO unit test for the property 'AttributesMask'
        }

        /// <summary>
        /// Test the property 'UrlKey'
        /// </summary>
        [Fact]
        public void UrlKeyTest()
        {
            // TODO unit test for the property 'UrlKey'
        }

        /// <summary>
        /// Test the property 'MaxSaleableQuantity'
        /// </summary>
        [Fact]
        public void MaxSaleableQuantityTest()
        {
            // TODO unit test for the property 'MaxSaleableQuantity'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'Variants'
        /// </summary>
        [Fact]
        public void VariantsTest()
        {
            // TODO unit test for the property 'Variants'
        }

        /// <summary>
        /// Test the property 'MediaVariantAttributes'
        /// </summary>
        [Fact]
        public void MediaVariantAttributesTest()
        {
            // TODO unit test for the property 'MediaVariantAttributes'
        }
    }
}
