/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductListProductsBySkuRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListProductsBySkuRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductListProductsBySkuRequest
        //private ProductListProductsBySkuRequest instance;

        public ProductListProductsBySkuRequestTests()
        {
            // TODO uncomment below to create an instance of ProductListProductsBySkuRequest
            //instance = new ProductListProductsBySkuRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListProductsBySkuRequest
        /// </summary>
        [Fact]
        public void ProductListProductsBySkuRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductListProductsBySkuRequest
            //Assert.IsType<ProductListProductsBySkuRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
    }
}
