/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductUpdateAssetEntryPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductUpdateAssetEntryPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductUpdateAssetEntryPayload
        //private ProductUpdateAssetEntryPayload instance;

        public ProductUpdateAssetEntryPayloadTests()
        {
            // TODO uncomment below to create an instance of ProductUpdateAssetEntryPayload
            //instance = new ProductUpdateAssetEntryPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductUpdateAssetEntryPayload
        /// </summary>
        [Fact]
        public void ProductUpdateAssetEntryPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductUpdateAssetEntryPayload
            //Assert.IsType<ProductUpdateAssetEntryPayload>(instance);
        }

        /// <summary>
        /// Test the property 'AssetGrn'
        /// </summary>
        [Fact]
        public void AssetGrnTest()
        {
            // TODO unit test for the property 'AssetGrn'
        }

        /// <summary>
        /// Test the property 'LocalizedAssetGrn'
        /// </summary>
        [Fact]
        public void LocalizedAssetGrnTest()
        {
            // TODO unit test for the property 'LocalizedAssetGrn'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
