/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductListProductsBySkuResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListProductsBySkuResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductListProductsBySkuResponse
        //private ProductListProductsBySkuResponse instance;

        public ProductListProductsBySkuResponseTests()
        {
            // TODO uncomment below to create an instance of ProductListProductsBySkuResponse
            //instance = new ProductListProductsBySkuResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListProductsBySkuResponse
        /// </summary>
        [Fact]
        public void ProductListProductsBySkuResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductListProductsBySkuResponse
            //Assert.IsType<ProductListProductsBySkuResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
    }
}
