/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductFieldMask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductFieldMaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductFieldMask
        //private ProductFieldMask instance;

        public ProductFieldMaskTests()
        {
            // TODO uncomment below to create an instance of ProductFieldMask
            //instance = new ProductFieldMask();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductFieldMask
        /// </summary>
        [Fact]
        public void ProductFieldMaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductFieldMask
            //Assert.IsType<ProductFieldMask>(instance);
        }

        /// <summary>
        /// Test the property 'Paths'
        /// </summary>
        [Fact]
        public void PathsTest()
        {
            // TODO unit test for the property 'Paths'
        }
    }
}
