/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkUpdateRequest
        //private ProductBulkUpdateRequest instance;

        public ProductBulkUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of ProductBulkUpdateRequest
            //instance = new ProductBulkUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkUpdateRequest
        /// </summary>
        [Fact]
        public void ProductBulkUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkUpdateRequest
            //Assert.IsType<ProductBulkUpdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ProductIds'
        /// </summary>
        [Fact]
        public void ProductIdsTest()
        {
            // TODO unit test for the property 'ProductIds'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
    }
}
