/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductListVariantsBySkuRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListVariantsBySkuRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductListVariantsBySkuRequest
        //private ProductListVariantsBySkuRequest instance;

        public ProductListVariantsBySkuRequestTests()
        {
            // TODO uncomment below to create an instance of ProductListVariantsBySkuRequest
            //instance = new ProductListVariantsBySkuRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListVariantsBySkuRequest
        /// </summary>
        [Fact]
        public void ProductListVariantsBySkuRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductListVariantsBySkuRequest
            //Assert.IsType<ProductListVariantsBySkuRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
    }
}
