/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductGetProductResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductGetProductResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductGetProductResponse
        //private ProductGetProductResponse instance;

        public ProductGetProductResponseTests()
        {
            // TODO uncomment below to create an instance of ProductGetProductResponse
            //instance = new ProductGetProductResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductGetProductResponse
        /// </summary>
        [Fact]
        public void ProductGetProductResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductGetProductResponse
            //Assert.IsType<ProductGetProductResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
    }
}
