/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductAssets
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductAssetsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAssets
        //private ProductAssets instance;

        public ProductAssetsTests()
        {
            // TODO uncomment below to create an instance of ProductAssets
            //instance = new ProductAssets();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAssets
        /// </summary>
        [Fact]
        public void ProductAssetsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductAssets
            //Assert.IsType<ProductAssets>(instance);
        }

        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Fact]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }
    }
}
