/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductListProductsByIdsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListProductsByIdsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductListProductsByIdsResponse
        //private ProductListProductsByIdsResponse instance;

        public ProductListProductsByIdsResponseTests()
        {
            // TODO uncomment below to create an instance of ProductListProductsByIdsResponse
            //instance = new ProductListProductsByIdsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListProductsByIdsResponse
        /// </summary>
        [Fact]
        public void ProductListProductsByIdsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductListProductsByIdsResponse
            //Assert.IsType<ProductListProductsByIdsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
    }
}
