/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkUpdateResponseV2Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkUpdateResponseV2ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkUpdateResponseV2Response
        //private ProductBulkUpdateResponseV2Response instance;

        public ProductBulkUpdateResponseV2ResponseTests()
        {
            // TODO uncomment below to create an instance of ProductBulkUpdateResponseV2Response
            //instance = new ProductBulkUpdateResponseV2Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkUpdateResponseV2Response
        /// </summary>
        [Fact]
        public void ProductBulkUpdateResponseV2ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkUpdateResponseV2Response
            //Assert.IsType<ProductBulkUpdateResponseV2Response>(instance);
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
    }
}
