/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductListProductsByIdsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListProductsByIdsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductListProductsByIdsRequest
        //private ProductListProductsByIdsRequest instance;

        public ProductListProductsByIdsRequestTests()
        {
            // TODO uncomment below to create an instance of ProductListProductsByIdsRequest
            //instance = new ProductListProductsByIdsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListProductsByIdsRequest
        /// </summary>
        [Fact]
        public void ProductListProductsByIdsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductListProductsByIdsRequest
            //Assert.IsType<ProductListProductsByIdsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
    }
}
