/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductAddMediaGalleryEntryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductAddMediaGalleryEntryResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAddMediaGalleryEntryResponse
        //private ProductAddMediaGalleryEntryResponse instance;

        public ProductAddMediaGalleryEntryResponseTests()
        {
            // TODO uncomment below to create an instance of ProductAddMediaGalleryEntryResponse
            //instance = new ProductAddMediaGalleryEntryResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAddMediaGalleryEntryResponse
        /// </summary>
        [Fact]
        public void ProductAddMediaGalleryEntryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductAddMediaGalleryEntryResponse
            //Assert.IsType<ProductAddMediaGalleryEntryResponse>(instance);
        }

        /// <summary>
        /// Test the property 'MediaGalleryEntry'
        /// </summary>
        [Fact]
        public void MediaGalleryEntryTest()
        {
            // TODO unit test for the property 'MediaGalleryEntry'
        }
    }
}
