/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductUpdateProductResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductUpdateProductResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductUpdateProductResponse
        //private ProductUpdateProductResponse instance;

        public ProductUpdateProductResponseTests()
        {
            // TODO uncomment below to create an instance of ProductUpdateProductResponse
            //instance = new ProductUpdateProductResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductUpdateProductResponse
        /// </summary>
        [Fact]
        public void ProductUpdateProductResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductUpdateProductResponse
            //Assert.IsType<ProductUpdateProductResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'ProductErrors'
        /// </summary>
        [Fact]
        public void ProductErrorsTest()
        {
            // TODO unit test for the property 'ProductErrors'
        }

        /// <summary>
        /// Test the property 'AttributeErrors'
        /// </summary>
        [Fact]
        public void AttributeErrorsTest()
        {
            // TODO unit test for the property 'AttributeErrors'
        }
    }
}
