/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductLocalizedAsset
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductLocalizedAssetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductLocalizedAsset
        //private ProductLocalizedAsset instance;

        public ProductLocalizedAssetTests()
        {
            // TODO uncomment below to create an instance of ProductLocalizedAsset
            //instance = new ProductLocalizedAsset();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductLocalizedAsset
        /// </summary>
        [Fact]
        public void ProductLocalizedAssetInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductLocalizedAsset
            //Assert.IsType<ProductLocalizedAsset>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
