/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductListVariantsBySkuResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListVariantsBySkuResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductListVariantsBySkuResponse
        //private ProductListVariantsBySkuResponse instance;

        public ProductListVariantsBySkuResponseTests()
        {
            // TODO uncomment below to create an instance of ProductListVariantsBySkuResponse
            //instance = new ProductListVariantsBySkuResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductListVariantsBySkuResponse
        /// </summary>
        [Fact]
        public void ProductListVariantsBySkuResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductListVariantsBySkuResponse
            //Assert.IsType<ProductListVariantsBySkuResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Variants'
        /// </summary>
        [Fact]
        public void VariantsTest()
        {
            // TODO unit test for the property 'Variants'
        }
    }
}
