/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductMediaGalleryEntryMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductMediaGalleryEntryMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductMediaGalleryEntryMetadata
        //private ProductMediaGalleryEntryMetadata instance;

        public ProductMediaGalleryEntryMetadataTests()
        {
            // TODO uncomment below to create an instance of ProductMediaGalleryEntryMetadata
            //instance = new ProductMediaGalleryEntryMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductMediaGalleryEntryMetadata
        /// </summary>
        [Fact]
        public void ProductMediaGalleryEntryMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductMediaGalleryEntryMetadata
            //Assert.IsType<ProductMediaGalleryEntryMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'Alt'
        /// </summary>
        [Fact]
        public void AltTest()
        {
            // TODO unit test for the property 'Alt'
        }
    }
}
