/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkUpdateRequestV2Payload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkUpdateRequestV2PayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkUpdateRequestV2Payload
        //private ProductBulkUpdateRequestV2Payload instance;

        public ProductBulkUpdateRequestV2PayloadTests()
        {
            // TODO uncomment below to create an instance of ProductBulkUpdateRequestV2Payload
            //instance = new ProductBulkUpdateRequestV2Payload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkUpdateRequestV2Payload
        /// </summary>
        [Fact]
        public void ProductBulkUpdateRequestV2PayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkUpdateRequestV2Payload
            //Assert.IsType<ProductBulkUpdateRequestV2Payload>(instance);
        }

        /// <summary>
        /// Test the property 'UpdateMask'
        /// </summary>
        [Fact]
        public void UpdateMaskTest()
        {
            // TODO unit test for the property 'UpdateMask'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
    }
}
