/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductUpdateMediaGalleryEntryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductUpdateMediaGalleryEntryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductUpdateMediaGalleryEntryRequest
        //private ProductUpdateMediaGalleryEntryRequest instance;

        public ProductUpdateMediaGalleryEntryRequestTests()
        {
            // TODO uncomment below to create an instance of ProductUpdateMediaGalleryEntryRequest
            //instance = new ProductUpdateMediaGalleryEntryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductUpdateMediaGalleryEntryRequest
        /// </summary>
        [Fact]
        public void ProductUpdateMediaGalleryEntryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductUpdateMediaGalleryEntryRequest
            //Assert.IsType<ProductUpdateMediaGalleryEntryRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'AssetGrn'
        /// </summary>
        [Fact]
        public void AssetGrnTest()
        {
            // TODO unit test for the property 'AssetGrn'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
