/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductProductResponseError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductProductResponseErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductProductResponseError
        //private ProductProductResponseError instance;

        public ProductProductResponseErrorTests()
        {
            // TODO uncomment below to create an instance of ProductProductResponseError
            //instance = new ProductProductResponseError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductProductResponseError
        /// </summary>
        [Fact]
        public void ProductProductResponseErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductProductResponseError
            //Assert.IsType<ProductProductResponseError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
