/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductDeleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductDeleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductDeleteResponse
        //private ProductDeleteResponse instance;

        public ProductDeleteResponseTests()
        {
            // TODO uncomment below to create an instance of ProductDeleteResponse
            //instance = new ProductDeleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductDeleteResponse
        /// </summary>
        [Fact]
        public void ProductDeleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductDeleteResponse
            //Assert.IsType<ProductDeleteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
