/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductProductVariant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductProductVariantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductProductVariant
        //private ProductProductVariant instance;

        public ProductProductVariantTests()
        {
            // TODO uncomment below to create an instance of ProductProductVariant
            //instance = new ProductProductVariant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductProductVariant
        /// </summary>
        [Fact]
        public void ProductProductVariantInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductProductVariant
            //Assert.IsType<ProductProductVariant>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'MaxSaleableQuantity'
        /// </summary>
        [Fact]
        public void MaxSaleableQuantityTest()
        {
            // TODO unit test for the property 'MaxSaleableQuantity'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
    }
}
