/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductGetProductByCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductGetProductByCodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductGetProductByCodeRequest
        //private ProductGetProductByCodeRequest instance;

        public ProductGetProductByCodeRequestTests()
        {
            // TODO uncomment below to create an instance of ProductGetProductByCodeRequest
            //instance = new ProductGetProductByCodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductGetProductByCodeRequest
        /// </summary>
        [Fact]
        public void ProductGetProductByCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductGetProductByCodeRequest
            //Assert.IsType<ProductGetProductByCodeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
