/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkUpdateAssetsEntriesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkUpdateAssetsEntriesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkUpdateAssetsEntriesRequest
        //private ProductBulkUpdateAssetsEntriesRequest instance;

        public ProductBulkUpdateAssetsEntriesRequestTests()
        {
            // TODO uncomment below to create an instance of ProductBulkUpdateAssetsEntriesRequest
            //instance = new ProductBulkUpdateAssetsEntriesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkUpdateAssetsEntriesRequest
        /// </summary>
        [Fact]
        public void ProductBulkUpdateAssetsEntriesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkUpdateAssetsEntriesRequest
            //Assert.IsType<ProductBulkUpdateAssetsEntriesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }
    }
}
