/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using product.Model;
using product.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace product.Test.Model
{
    /// <summary>
    ///  Class for testing ProductBulkUpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductBulkUpdateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductBulkUpdateResponse
        //private ProductBulkUpdateResponse instance;

        public ProductBulkUpdateResponseTests()
        {
            // TODO uncomment below to create an instance of ProductBulkUpdateResponse
            //instance = new ProductBulkUpdateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductBulkUpdateResponse
        /// </summary>
        [Fact]
        public void ProductBulkUpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductBulkUpdateResponse
            //Assert.IsType<ProductBulkUpdateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ProductResponse'
        /// </summary>
        [Fact]
        public void ProductResponseTest()
        {
            // TODO unit test for the property 'ProductResponse'
        }
    }
}
