/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = product.Client.OpenAPIDateConverter;

namespace product.Model
{
    /// <summary>
    /// EntitymanagerUpdateAttributeRequestPayload
    /// </summary>
    [DataContract(Name = "entitymanagerUpdateAttributeRequestPayload")]
    public partial class EntitymanagerUpdateAttributeRequestPayload : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets RenderAs
        /// </summary>
        [DataMember(Name = "renderAs", EmitDefaultValue = false)]
        public EntitymanagerRenderAs? RenderAs { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EntitymanagerUpdateAttributeRequestPayload" /> class.
        /// </summary>
        /// <param name="label">label.</param>
        /// <param name="varDefault">varDefault.</param>
        /// <param name="sort">sort.</param>
        /// <param name="groupCode">groupCode.</param>
        /// <param name="title">title.</param>
        /// <param name="renderAs">renderAs.</param>
        public EntitymanagerUpdateAttributeRequestPayload(string label = default(string), string varDefault = default(string), int sort = default(int), string groupCode = default(string), Dictionary<string, string> title = default(Dictionary<string, string>), EntitymanagerRenderAs? renderAs = default(EntitymanagerRenderAs?))
        {
            this.Label = label;
            this.VarDefault = varDefault;
            this.Sort = sort;
            this.GroupCode = groupCode;
            this.Title = title;
            this.RenderAs = renderAs;
        }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name = "label", EmitDefaultValue = false)]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets VarDefault
        /// </summary>
        [DataMember(Name = "default", EmitDefaultValue = false)]
        public string VarDefault { get; set; }

        /// <summary>
        /// Gets or Sets Sort
        /// </summary>
        [DataMember(Name = "sort", EmitDefaultValue = false)]
        public int Sort { get; set; }

        /// <summary>
        /// Gets or Sets GroupCode
        /// </summary>
        [DataMember(Name = "groupCode", EmitDefaultValue = false)]
        public string GroupCode { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public Dictionary<string, string> Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EntitymanagerUpdateAttributeRequestPayload {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  VarDefault: ").Append(VarDefault).Append("\n");
            sb.Append("  Sort: ").Append(Sort).Append("\n");
            sb.Append("  GroupCode: ").Append(GroupCode).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  RenderAs: ").Append(RenderAs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
