/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = product.Client.OpenAPIDateConverter;

namespace product.Model
{
    /// <summary>
    /// Defines entitymanagerTypes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EntitymanagerTypes
    {
        /// <summary>
        /// Enum TEXT for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")]
        TEXT = 1,

        /// <summary>
        /// Enum NUMBER for value: NUMBER
        /// </summary>
        [EnumMember(Value = "NUMBER")]
        NUMBER = 2,

        /// <summary>
        /// Enum BOOLEAN for value: BOOLEAN
        /// </summary>
        [EnumMember(Value = "BOOLEAN")]
        BOOLEAN = 3,

        /// <summary>
        /// Enum DATETIME for value: DATETIME
        /// </summary>
        [EnumMember(Value = "DATETIME")]
        DATETIME = 4,

        /// <summary>
        /// Enum EXTERNAL for value: EXTERNAL
        /// </summary>
        [EnumMember(Value = "EXTERNAL")]
        EXTERNAL = 5,

        /// <summary>
        /// Enum EMBED for value: EMBED
        /// </summary>
        [EnumMember(Value = "EMBED")]
        EMBED = 6,

        /// <summary>
        /// Enum FLOAT32 for value: FLOAT32
        /// </summary>
        [EnumMember(Value = "FLOAT32")]
        FLOAT32 = 7
    }

}
