/*
 * Product Service
 *
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = product.Client.OpenAPIDateConverter;

namespace product.Model
{
    /// <summary>
    /// ProductUpdateProductResponse
    /// </summary>
    [DataContract(Name = "productUpdateProductResponse")]
    public partial class ProductUpdateProductResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdateProductResponse" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="productErrors">productErrors.</param>
        /// <param name="attributeErrors">attributeErrors.</param>
        public ProductUpdateProductResponse(bool success = default(bool), List<ProductProductResponseError> productErrors = default(List<ProductProductResponseError>), List<ProductAttributeResponseError> attributeErrors = default(List<ProductAttributeResponseError>))
        {
            this.Success = success;
            this.ProductErrors = productErrors;
            this.AttributeErrors = attributeErrors;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets ProductErrors
        /// </summary>
        [DataMember(Name = "productErrors", EmitDefaultValue = false)]
        public List<ProductProductResponseError> ProductErrors { get; set; }

        /// <summary>
        /// Gets or Sets AttributeErrors
        /// </summary>
        [DataMember(Name = "attributeErrors", EmitDefaultValue = false)]
        public List<ProductAttributeResponseError> AttributeErrors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductUpdateProductResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  ProductErrors: ").Append(ProductErrors).Append("\n");
            sb.Append("  AttributeErrors: ").Append(AttributeErrors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
